apiVersion: apps/v1
kind: Deployment
metadata:
  name: contract
  labels:
    app: contract
spec:
  replicas: 1
  selector:
    matchLabels:
      app: contract
  template:
    metadata:
      labels:
        app: contract
    spec:
      containers:
        - name: contract
          image: user0101.azurecr.io/contract:v1
          ports:
            - containerPort: 8080
          env:
            - name: LOCATION
              valueFrom:
                configMapKeyRef:
                  name: applocation
                  key: applocationvalue
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8088
            initialDelaySeconds: 20
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5


---


apiVersion: v1
kind: Service
metadata:
  name: contract
  labels:
    app: contract
spec:
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: contract